### ISSUE TITLE
Images are causing odd glitches with page transitions.

### ISSUE THREAD

**Issue by jpasholk** [wanoo21/tailwind-astro-starting-blog#12]
**Describe the bug**

Okay, this is a wierd one...

After forking the theme and starting to add my own content I noticed some odd behavior. When clicking on a link to a post or page that has an image in it the transition animations glitch out, causing the page to flicker in Safari and the mobile nav to fly by. In Chrome it doesn't flash, just does the nav thing...

**To Reproduce**

1. Fork the theme.
2. Add a new page with an image in `src`, in my case `src/assets`,
3. Then either build it through Netlify or run `npm run build`, then run `npm run preview`.
4. Click a link to one of those pages.
5. It should glitch like I described.

**Expected behavior**

Images should be able to be put in `src` so Astro can process them with the `<Image />` component.

**Screenshots**

![Bug in action](https://jpshlk.com/trasition-glitch.gif)

**Desktop (please complete the following information):**
 - OS: MacOS - Ventura 13.5
 - Browser: Safari - 16.6 (18615.3.12.11.2), Chrome - 119.0.6045.159
 
**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 17.2
 - Browser Safari - 17

**Additional context**

I documented this for my ongoing journey about learning webdev as a complete noob [here](https://jpshlk.com/blog/odd-behavior-with-transitions/).

Also, I couldn't find the `<head>` to check if the `<ViewTransitions />` component was in there. I found it under the `html` tag in `RootLayout` though. I thought it was supposed to go in the head, per the [Astro Docs](https://docs.astro.build/en/guides/view-transitions/#adding-view-transitions-to-a-page). Any insight on this?

Thanks again for the awesome theme and for fixing the last issue I reported!

**Comment by wanoo21** [comment]
The `src/components/BaseHead.astro` file is what you're looking for 😉. Thanks for reporting this, I'll see what I can do!

**Comment by jpasholk** [comment]
I looked in there but there isn't a `<head/>` tag, yet there is one in the redered html. Where is it coming from?

I ended up fixing it with with this:

```
<head>
<ViewTransitions />
<BaseHead title={title} description={description}/>
<head/>
```

[Link](https://github.com/jpasholk/jpshlk-blog/blob/12f1f09c40fd32b2c21d5fbb39378fd0b904443b/src/layouts/RootLayout.astro#L18-L21)

**Comment by wanoo21** [comment]
SO this solved the issue?

**Comment by jpasholk** [comment]
@wanoo21 Yeah, I think so. But I'm still curious where the `<head>` tag is coming from. If you just forgot to include one, I can try to submit a pull request for a fix, if you'd like.

I've got a few other questions/requests as well, but I'll create those as separate issues or maybe in the discussions, whatever you prefer.

Love the theme so far, by the way

**Comment by wanoo21** [comment]
@jpasholk it seems that the `head` tag was missing, I pushed a fix now and some other updates. 

Thank you for your appreciation, let's make it even better 💪🏼, for suggestions and requests a better place is the discussion section 🙂.
