### ISSUE TITLE
Documentation for how to add Tags

### ISSUE THREAD

**Issue by danielrosehill** [wanoo21/tailwind-astro-starting-blog#16]
I assumed that after creating the `.mdx` that the frontmatter format for creating tags would be like this:

![image](https://github.com/wanoo21/tailwind-astro-starting-blog/assets/40233203/e66209ca-1ccc-4c00-8b94-cbd0bf65edfb)

But it seems that it is not so:

![image](https://github.com/wanoo21/tailwind-astro-starting-blog/assets/40233203/7eab7917-197a-4bf2-8593-2e579cd7d14d)

Is there any chance one of the sample blog posts could have some tags added so that we can know how to format them correctly in the front matter? I've tried lots of different permutations and keep getting the same error

**Comment by wanoo21** [comment]
Hey @danielrosehill, did you try it like this?
 
```mdx
tags:
  - "Linux"
  - "Ubuntu"
```
or
```mdx
tags: ["Linux", "Ubuntu"]
```
